 # Method C Matrix
 -------------------------------------------------------------------------------------------
  ## How to run This Program 
   ![Jupyter](https://cdn-images-1.medium.com/max/1600/1*LPnY8nOLg4S6_TG0DEXwsg.png) 
  * Need Jupyter Notebook or Install Anaconda Python
  * Copy this File into locate C:\Users\Name of user in PC
  * Open Jupyter Notebook and run this file
  * Click Run or Press Shift + Enter to process 

  ![Matrix](https://cdn3.movieweb.com/i/article/gIdrZFTvO1nsC16dRaTBMOzqaabBjj/1150:50/The-Matrix-4-Reboot-Plot-Keanu-Reeves.jpg)

In [1]:
# Powered By Jupyter Notebook
# System linear equation
# Simplified Matrix form for this system (Ax = b). 
# C.1 Find determinant of A without using recursion 
# Using Library function from Python
import numpy as np
# define matrix A using Numpy arrays
#𝑥 + 3𝑦 − 2𝑧  #3𝑥 + 2𝑦 + 6𝑧  #2𝑥 + 4𝑦 + 3𝑧
A = np.array([[1, 3, -2],[3, 2, 6],[2, 4, 3]]) 

#define matrix    B
# 𝑥 + 3𝑦 − 2𝑧 = 1 
#3𝑥 + 2𝑦 + 6𝑧 = −2
#2𝑥 + 4𝑦 + 3𝑧 = 2 
B = np.array([1, -2, 2]) 

# linalg.solve is the function of NumPy to solve a system of linear scalar equations
print ("Solutions:\n",np.linalg.solve(A, B ))
# Result Solutions:  [-2.4  1.4  0.4]

Solutions:
 [-2.4  1.4  0.4]


In [2]:
# C.2 Find x, y, and z using Cramer’s rule. 
from numpy import linalg    
# 𝑥 + 3𝑦 − 2𝑧 = 1 
#3𝑥 + 2𝑦 + 6𝑧 = −2
#2𝑥 + 4𝑦 + 3𝑧 = 2     
#1 3 -2
# 3 2 6
#2 4 3
A=[[1,3,-2],[3,2,6],[2,4,3]]
# B is equal 1 , -2 , 2 
B=[1,-2,2]
C=[[1,3,-2],[3,2,6],[2,4,3]]
X=[]
for i in range(0,len(B)):
    for j in range(0,len(B)):
        C[j][i]=B[j]
        if i>0:
            C[j][i-1]=A[j][i-1]
            # Use linalg or Linear Algebra Library to find Determinant
    X.append(round(linalg.det(C)/linalg.det(A),1)) 
print("x=",X[0],'y=',X[1],'z=',X[2])
# Result x= -2.4 y= 1.4 z= 0.4

x= -2.4 y= 1.4 z= 0.4


In [3]:
#C.3.1 Find Inverse of A by Minor
# Use linalg or Linear Algebra Library to solve Inverse
A=[[1,3,-2],[3,2,6],[2,4,3]]
Minor = np.linalg.inv(A)
print(Minor)
# Result [[ 0.72  0.68 -0.88]
#           [-0.12 -0.28  0.48]
#          [-0.32 -0.08  0.28]]

[[ 0.72  0.68 -0.88]
 [-0.12 -0.28  0.48]
 [-0.32 -0.08  0.28]]


In [4]:
#C.3.2 Find Inverse by using Cofactor
A=[[1,3,-2],[3,2,6],[2,4,3]]
# Use linalg or Linear Algebra Library to find by inverse * determinant
Cofactor =  np.linalg.inv(A).T * np.linalg.det(A)
print(Cofactor)

[[-18.   3.   8.]
 [-17.   7.   2.]
 [ 22. -12.  -7.]]


In [5]:
#C.3.3 Find Inverse by using Adjugate
import numpy as np
# us Numpy or Numeric Python Package to find transpose from cofactor
print(np.transpose(Cofactor))

[[-18. -17.  22.]
 [  3.   7. -12.]
 [  8.   2.  -7.]]
