# A False Position method 
 -------------------------------------------------------------------------------------------
  ## How to run This Program 
   ![Jupyter](https://cdn-images-1.medium.com/max/1600/1*LPnY8nOLg4S6_TG0DEXwsg.png) 
  * Need Jupyter Notebook or Install Anaconda Python
  * Copy this File into locate C:\Users\Name of user in PC
  * Open Jupyter Notebook and run this file
  * Click Run or Press Shift + Enter to process 


In [1]:
 # A find interval
from math import * 
import numpy as np
def ln(x, M):
    return np.log(x) - M


def false_si_postition(M):
    i = 1
    while True:
        if(np.log(i) < M): i += 1
        else: 
            break
    xl = i - 1
    print("Value of Xl is ",xl)
    xu = i
    print("Value of Xu is ",xu)
    xr = xu
    ea = 100
    es = (0.5 * pow(10,2-M))
    errsig = (0.5 * 10**2-M)
    print("Value of Error significant is " , errsig)
    print("Value of Es is " , es)
    while ea > es:
        prev_xr = xr
        xr = xu - ln(xu, M)*((xu - xl)/(ln(xu, M) - ln(xl, M)))
        if ln(xr, 5) == 0: break
        elif ln(xl, M)*ln(xr, M) < 0:
            xu = xr
        else: xl = xr
        ea = (xr - prev_xr)/xr * 100
        ea = abs(ea)
        print("Value of Ea is " , ea)
    return xr
    
a = float(input("Enter value : "))
if(a<0):print("error")
else:print(f"Value or Xr is : {false_si_postition(a)}" ) 

Enter value : 3
Value of Xl is  20
Value of Xu is  21
Value of Error significant is  47.0
Value of Es is  0.05
Value of Ea is  4.542776725018565
Value of Ea is  0.009608884844831606
Value or Xr is : 20.085541044399335


# B 2.1 Golden Section Search(GSS) to find the value of x at the local minimum
 -------------------------------------------------------------------------------------------
  ## How to run This Program 
   ![Jupyter](https://cdn-images-1.medium.com/max/1600/1*LPnY8nOLg4S6_TG0DEXwsg.png) 
  * Need Jupyter Notebook or Install Anaconda Python
  * Copy this File into locate C:\Users\Name of user in PC
  * Open Jupyter Notebook and run this file
  * Click Run or Press Shift + Enter to process 


In [2]:
import math
invphi = (math.sqrt(5) - 1) / 2 # 1/phi                                                                                                                     
invphi2 = (3 - math.sqrt(5)) / 2 # 1/phi^2                                                                                                                  

def gssrec(f,a,b,tol=1e-5,h=None,c=None,d=None,fc=None,fd=None):
 
    (a,b)=(min(a,b),max(a,b))
    if h == None: h=b-a
    if h <= tol: return (a,b)
    if c == None: c = a + invphi2*h
    if d == None: d = a + invphi*h
    if fc == None: fc = f(c)
    if fd == None: fd = f(d)
    if fc < fd:
        return gssrec(f,a,d,tol,h*invphi,c=None,fc=None,d=c,fd=fc)
    else:
        return gssrec(f,c,b,tol,h*invphi,c=d,fc=fd,d=None,fd=None)


f = lambda x: pow(x,3)-(3*pow(x,2))-9*x+18;
a = 0
b = 5
tol = 1e-5
(c,d) = gssrec(f,a,b,tol)
print("Minimum Value of f(x) is : ",c)

Minimum Value of f(x) is :  3.9148498369237834


In [3]:
import math
invphi = (math.sqrt(5) - 1) / 2 # 1/phi                                                                                                                     
invphi2 = (3 - math.sqrt(5)) / 2 # 1/phi^2                                                                                                                  

def gssrec(f,a,b,tol=1e-5,h=None,c=None,d=None,fc=None,fd=None):
 
    (a,b)=(min(a,b),max(a,b))
    if h == None: h=b-a
    if h <= tol: return (a,b)
    if c == None: c = a + invphi2*h
    if d == None: d = a + invphi*h
    if fc == None: fc = f(c)
    if fd == None: fd = f(d)
    if fc < fd:
        return gssrec(f,a,d,tol,h*invphi,c=None,fc=None,d=c,fd=fc)
    else:
        return gssrec(f,c,b,tol,h*invphi,c=d,fc=fd,d=None,fd=None)


f = lambda x: (3*math.sin(x))+pow(math.cos(x),2);
a = 2*math.pi
b = math.pi
tol = 1e-5
(c,d) = gssrec(f,a,b,tol)
print("Minimum Value of g(x) is : ",c)

Minimum Value of g(x) is :  4.7123854039228945


# B 2.2 Find Maximum by using parabolic interpolation technique

In [9]:
#B2.1 parabolic interpolation technique to find the maximum of the function f(x)
import math
def fx(x):
    return x**3-6*(x**2)+x-4;
#f = lambda x: (3*math.sin(x))+pow(math.cos(x),2);   
x1 = -2
x2 = 0
x3 = 2
es = 0.05
iteration = 0;
max_iteration = 20;
xopt = 0;
while  iteration< 15:
    xopt_previous = xopt;
    alpha1 = (x2-x1)*(x2-x1)*(fx(x2)-fx(x3));
    alpha2 = (x2-x3)*(x2-x3)*(fx(x2)-fx(x1));
    beta1 = (x2-x1)*(fx(x2)-fx(x3));
    beta2 = (x2-x3)*(fx(x2)-fx(x1));
    gamma = (alpha1 - alpha2)/(beta1 - beta2);
    x4 = x2 - (0.5 * gamma);
    iteration = iteration + 1;
    print(f"x1={x1}, x2 = {x2}, x3 = {x3}, x4={x4}")
    if x4 > x2:
        x1 = x2
        x2 = x4;
    else :
        x3 = x2
        x2 = x4;
    xopt = x4;
    iteration = iteration + 1;
    ea = (abs(xopt-xopt_previous)/xopt)*100;
    print(f"Value of f(x) is {fx(xopt)}");
    if( ea < es or iteration>= max_iteration):
        print(f"Value of xopt is {xopt} , value of ea is {ea} , value of es is {es}")

x1=-2, x2 = 0, x3 = 2, x4=0.4166666666666667
Value of f(x) is -4.552662037037037
x1=0, x2 = 0.4166666666666667, x3 = 2, x4=0.023255813953488302
Value of f(x) is -3.9799766058334485
x1=0, x2 = 0.023255813953488302, x3 = 0.4166666666666667, x4=0.08905542000697153
Value of f(x) is -3.9578235002228834
x1=0.023255813953488302, x2 = 0.08905542000697153, x3 = 0.4166666666666667, x4=0.0869245799926733
Value of f(x) is -3.957753923726664
x1=0.023255813953488302, x2 = 0.0869245799926733, x3 = 0.08905542000697153, x4=0.08517553077380323
Value of f(x) is -3.9577357579900423
x1=0.023255813953488302, x2 = 0.08517553077380323, x3 = 0.0869245799926733, x4=0.085155421399076
Value of f(x) is -3.957735753440538
Value of xopt is 0.085155421399076 , value of ea is 0.0236149083603078 , value of es is 0.05
x1=0.023255813953488302, x2 = 0.085155421399076, x3 = 0.08517553077380323, x4=0.08514599435378808
Value of f(x) is -3.957735752907294
Value of xopt is 0.08514599435378808 , value of ea is 0.011071625106342

In [7]:
#B2.1 parabolic interpolation technique to find the maximum of the function f(x)
import math
def gx(x):
    return (3*math.sin(x))+pow(math.cos(x),2);
#f = lambda x: (3*math.sin(x))+pow(math.cos(x),2);   
x1 = -(math.pi/2)
x2 = 0
x3 = math.pi
es = 0.05
iteration = 0;
max_iteration = 20;
xopt = 0;
while  iteration< 4:
    xopt_previous = xopt;
    alpha1 = (x2-x1)*(x2-x1)*(gx(x2)-gx(x3));
    alpha2 = (x2-x3)*(x2-x3)*(gx(x2)-gx(x1));
    beta1 = (x2-x1)*(gx(x2)-gx(x3));
    beta2 = (x2-x3)*(gx(x2)-gx(x1));
    gamma = (alpha1 - alpha2)/(beta1 - beta2);
    x4 = x2 - (0.5 * gamma);
    iteration = iteration + 1;
    print(f"x1={x1}, x2 = {x2}, x3 = {x3}, x4={x4}")
    if x4 > x2:
        x1 = x2
        x2 = x4;
    else :
        x3 = x2
        x2 = x4;
    xopt = x4;
    iteration = iteration + 1;
    ea = (abs(xopt-xopt_previous)/xopt)*100;
    print(f"Value of g(x) is {gx(xopt)}");
    if( ea < es or iteration>= max_iteration):
        print(f"Value of xopt is {xopt} , value of ea is {ea} , value of es is {es}")

x1=-1.5707963267948966, x2 = 0, x3 = 3.141592653589793, x4=1.5707963267948966
Value of g(x) is 3.0
x1=0, x2 = 1.5707963267948966, x3 = 3.141592653589793, x4=1.5707963267948966
Value of g(x) is 3.0
Value of xopt is 1.5707963267948966 , value of ea is 0.0 , value of es is 0.05


 # Method C Matrix
 -------------------------------------------------------------------------------------------
  ## How to run This Program 
   ![Jupyter](https://cdn-images-1.medium.com/max/1600/1*LPnY8nOLg4S6_TG0DEXwsg.png) 
  * Need Jupyter Notebook or Install Anaconda Python
  * Copy this File into locate C:\Users\Name of user in PC
  * Open Jupyter Notebook and run this file
  * Click Run or Press Shift + Enter to process 

  ![Matrix](https://cdn3.movieweb.com/i/article/gIdrZFTvO1nsC16dRaTBMOzqaabBjj/1150:50/The-Matrix-4-Reboot-Plot-Keanu-Reeves.jpg)

In [6]:
# Powered By Jupyter Notebook
# System linear equation
# Simplified Matrix form for this system (Ax = b). 
# C.1 Find determinant of A without using recursion 
# Using Library function from Python
import numpy as np
# define matrix A using Numpy arrays
#𝑥 + 3𝑦 − 2𝑧  #3𝑥 + 2𝑦 + 6𝑧  #2𝑥 + 4𝑦 + 3𝑧
A = np.array([[1, 3, -2],[3, 2, 6],[2, 4, 3]]) 

#define matrix    B
# 𝑥 + 3𝑦 − 2𝑧 = 1 
#3𝑥 + 2𝑦 + 6𝑧 = −2
#2𝑥 + 4𝑦 + 3𝑧 = 2 
B = np.array([1, -2, 2]) 

# linalg.solve is the function of NumPy to solve a system of linear scalar equations
print ("Solutions:\n",np.linalg.solve(A, B ))
# Result Solutions:  [-2.4  1.4  0.4]

Solutions:
 [-2.4  1.4  0.4]


In [7]:
# C.2 Find x, y, and z using Cramer’s rule. 
from numpy import linalg    
# 𝑥 + 3𝑦 − 2𝑧 = 1 
#3𝑥 + 2𝑦 + 6𝑧 = −2
#2𝑥 + 4𝑦 + 3𝑧 = 2     
#1 3 -2
# 3 2 6
#2 4 3
A=[[1,3,-2],[3,2,6],[2,4,3]]
# B is equal 1 , -2 , 2 
B=[1,-2,2]
C=[[1,3,-2],[3,2,6],[2,4,3]]
X=[]
for i in range(0,len(B)):
    for j in range(0,len(B)):
        C[j][i]=B[j]
        if i>0:
            C[j][i-1]=A[j][i-1]
            # Use linalg or Linear Algebra Library to find Determinant
    X.append(round(linalg.det(C)/linalg.det(A),1)) 
print("x=",X[0],'y=',X[1],'z=',X[2])
# Result x= -2.4 y= 1.4 z= 0.4

x= -2.4 y= 1.4 z= 0.4


In [8]:
#C.3.1 Find Inverse of A by Minor
# Use linalg or Linear Algebra Library to solve Inverse
import numpy as np
A=[[1,3,-2],[3,2,6],[2,4,3]]
Minor = (np.linalg.inv(A).T/-1 )*np.linalg.det(A)
print(Minor)


[[ 18.  -3.  -8.]
 [ 17.  -7.  -2.]
 [-22.  12.   7.]]


In [9]:
#C.3.2 Find Inverse by using Cofactor
A=[[1,3,-2],[3,2,6],[2,4,3]]
# Use linalg or Linear Algebra Library to find by inverse * determinant
Cofactor =  np.linalg.inv(A).T * np.linalg.det(A)
print(Cofactor)

[[-18.   3.   8.]
 [-17.   7.   2.]
 [ 22. -12.  -7.]]


In [10]:
#C.3.3 Find Inverse by using Adjugate
import numpy as np
# us Numpy or Numeric Python Package to find transpose from cofactor
print(np.transpose(Cofactor))

[[-18. -17.  22.]
 [  3.   7. -12.]
 [  8.   2.  -7.]]
